### ISSUE TITLE
Image size exceeds localStorage quota

### ISSUE THREAD

**Issue by sgimeno** [sgimeno/pagediff-extension#5]
Loading big image files can be an issue if we try to store the imageData base64 serialized in localStorage. I get this with the `1920.png` screenshot file:

```
Error in event handler for runtime.onMessage: QuotaExceededError: Failed to set the 'pd_img_src' property on 'Storage': Setting the value of 'pd_img_src' exceeded the quota.
    at renderImage (chrome-extension://nbakdplemhmgcombjjmeegokdbmpdhcl/scripts/content.js:24:27)
    at chrome-extension://nbakdplemhmgcombjjmeegokdbmpdhcl/scripts/content.js:68:7handler @ extensions::uncaught_exception_handler:8exports.handle @ 
...
```

**Comment by horacioh** [comment]
I think we can use a free image hosting or a simple Parse app to store the images for a specific period of time. there are some free solutions out there:
- [Thumbsnap API](http://thumbsnap.com/api)
- [cloudinary](http://cloudinary.com/pricing)
- [Parse](parse.com): i can create the app myself
- [UploadCare](https://uploadcare.com/pricing/)
- or maybe a heroku app??

I was thinking about a Parse app that has a background job that delete all the images uploaded in 24 hours from the upload time (or maybe more time in the beginning)

**Comment by sgimeno** [comment]
I'd prefer to avoid any external resources so the extension works offline.

**Comment by horacioh** [comment]
is there a solution to store a file somwhere we can get access to? cause asking to reduce the file size i dont think would be the only way...

**Comment by horacioh** [comment]
I found this:
- _[chrome.fileSystemProvider](https://developer.chrome.com/extensions/fileSystemProvider):_ Use the chrome.fileSystemProvider API to create file systems, that can be accessible from the file manager on Chrome OS.
- _[chrome.fileBrowserHandler](https://developer.chrome.com/extensions/fileBrowserHandler):_ Use the chrome.fileBrowserHandler API to extend the Chrome OS file browser. For example, you can use this API to enable users to upload files to your website.

hope this helps :)
